services:
  app:
    build:
      context: ../
      dockerfile: ./docker_build/app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../src/.env
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ../src/alembic:/src/alembic
    container_name: coffee_shop_app

  init_script:
    build:
      context: ../
      dockerfile: ./docker_build/app/Dockerfile
    env_file:
      - ../src/.env
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ../src/alembic:/src/alembic
    command: python -m scripts.create_first_admin
    restart: "no"
