services:
  pg:
    image: postgres:16.4
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    # expose:
    #   - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ../src/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 3
